// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhzrzy2Rhr0sLVhL7BC_B00zSzoKrJdDM',
    appId: '1:231228833513:web:897b2f6ee16df4d3193a78',
    messagingSenderId: '231228833513',
    projectId: 'mesas-nsps-app',
    authDomain: 'mesas-nsps-app.firebaseapp.com',
    storageBucket: 'mesas-nsps-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHW07nD55KufohzWRq4CbJ6YNeeZekmN0',
    appId: '1:231228833513:android:ee7755182ae93a8d193a78',
    messagingSenderId: '231228833513',
    projectId: 'mesas-nsps-app',
    storageBucket: 'mesas-nsps-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgU8ybu7-SOJGAPg-mv3YyTmMAkg_b-iw',
    appId: '1:231228833513:ios:889fd8f0ea794c3b193a78',
    messagingSenderId: '231228833513',
    projectId: 'mesas-nsps-app',
    storageBucket: 'mesas-nsps-app.firebasestorage.app',
    iosBundleId: 'com.example.mesasnsps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgU8ybu7-SOJGAPg-mv3YyTmMAkg_b-iw',
    appId: '1:231228833513:ios:889fd8f0ea794c3b193a78',
    messagingSenderId: '231228833513',
    projectId: 'mesas-nsps-app',
    storageBucket: 'mesas-nsps-app.firebasestorage.app',
    iosBundleId: 'com.example.mesasnsps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhzrzy2Rhr0sLVhL7BC_B00zSzoKrJdDM',
    appId: '1:231228833513:web:e7be865a53cfa3e6193a78',
    messagingSenderId: '231228833513',
    projectId: 'mesas-nsps-app',
    authDomain: 'mesas-nsps-app.firebaseapp.com',
    storageBucket: 'mesas-nsps-app.firebasestorage.app',
  );
}
